server:
  port: 8081

spring:
  application:
    name: ms-andesstay-reservations

  profiles:
    default: local

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/24b1cd18-d18e-4855-bcaf-51ac2db566d5/v2.0
