spring:
  datasource:
    url: jdbc:h2:file:./data/reservations;MODE=Oracle;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      show-details: always

  health:
    rabbit:
      enabled: true