server:
  port: 8081

spring:
  application:
    name: ms-andesstay-reservations

  profiles:
    default: local

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:andesstay}
    password: ${RABBITMQ_PASSWORD:andesstay_dev}
    virtual-host: /

    connection-timeout: 5s

    publisher-confirm-type: correlated
    publisher-returns: true

    template:
      mandatory: true
      retry:
        enabled: true
        initial-interval: 1s
        max-interval: 5s
        multiplier: 2.0
        max-retries: 3

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/24b1cd18-d18e-4855-bcaf-51ac2db566d5/v2.0